"""Added create and end date for telemetry for better performance review

Revision ID: d9aa890c756c
Revises: 26394f8a2e92
Create Date: 2024-04-30 23:11:06.304190

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "d9aa890c756c"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("telemetry", schema=None) as batch_op:
        batch_op.add_column(sa.Column("end_date", sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("telemetry", schema=None) as batch_op:
        batch_op.drop_column("end_date")

    # ### end Alembic commands ###
